name: InkTime
description: Minimal e-ink inspired clock, weather, forecasts & world time dashboard.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.2.2
  intl: 0.20.2
  shared_preferences: ^2.3.3
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#F5F0EB"
  adaptive_icon_foreground: assets/icon/app_icon_foreground.png
